# Generated by Django 5.2.2 on 2025-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('shirts', 'Shirts'), ('pants', 'Pants'), ('watches', 'Watches'), ('caps', 'Caps'), ('perfume', 'Perfume'), ('socks', 'Socks'), ('underwear', 'Underwear'), ('shorts', 'Shorts')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
