# Generated by Django 5.2.2 on 2025-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Default value'),
            preserve_default=False,
        ),
    ]
