# Generated by Django 5.2.2 on 2025-06-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
